version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: test-api
    container_name: recipe-finder-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      ConnectionStrings__PostgreSQLConnection: "User ID=postgres;Password=postgres;Server=db;Port=5432;Database=dbname;"
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - db 
    networks:
      - dev

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipefinderdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
    db_data: 